// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------- //
// pwm_waveform_output //
// ------------------- //

#define pwm_waveform_output_wrap_target 0
#define pwm_waveform_output_wrap 4
#define pwm_waveform_output_pio_version 0

static const uint16_t pwm_waveform_output_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0x6020, //  1: out    x, 32                      
    0x80a0, //  2: pull   block                      
    0x6001, //  3: out    pins, 1                    
    0x0044, //  4: jmp    x--, 4                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pwm_waveform_output_program = {
    .instructions = pwm_waveform_output_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pwm_waveform_output_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pwm_waveform_output_wrap_target, offset + pwm_waveform_output_wrap);
    return c;
}
#endif

